### ISSUE TITLE
Valid types inconsistency

### ISSUE THREAD

**Issue by Jorisvansteenbrugge** [simonvh/pita#6]
pita/config.py : `VALID_TYPES = [bed, gff, gff3, gtf]`
whereas pita/io.py has options for
`bed` and `[gff, gff3, gtf3]` 

in other words: when using gtf the program crashes, because 1 class asks you to use `gtf` as type and the other class asks for `gtf3`

**Comment by Jorisvansteenbrugge** [comment]
if statements using the specified types are checked in the following classes:
pita/config.py (uses `gtf`)
pita/io.py (uses `gtf3`)
pita/model.py (uses `gtf`)

**Comment by simonvh** [comment]
It should be gtf instead of gtf3

**Comment by Jorisvansteenbrugge** [comment]
It is fixed
